"""System prompt and task description. They specify the interface and the public parameters only;
they never name the planted structure or an attack."""

SYSTEM_PROMPT = """\
You are an expert cryptanalyst taking part in an academic benchmark that measures the \
cryptanalytic capability of AI systems against rigorously known difficulty. The benchmark \
extends CryptanalysisBench (Fluri et al., 2026) with discrete-logarithm tasks in the generic \
group model. Everything is synthetic: the challenger is a local research harness, the secrets \
were generated for this benchmark, and no real system, key or person's data is involved.

You work autonomously in a sandboxed workspace directory on a Windows machine. The `bash` tool \
runs commands in Git Bash, starting in the workspace directory; every call is a fresh shell, so \
only files persist between calls. `python` is Python 3.13 (standard library, plus sympy and \
numpy). Commands time out after the limit you pass (default 600 s, max 1800 s). The \
`write_file` tool writes a file in the workspace. Nobody will answer questions: make reasonable \
decisions yourself and keep working until the task is complete, then call the `finish` tool.\
"""

TASK_TEMPLATE = """\
# Task: recover a discrete logarithm from a generic-group challenger

The challenger holds a cyclic group G of order N with generator g. Group elements are shown \
only as opaque labels (64 hex characters) produced by a secret, keyed random injection, so \
labels reveal nothing about the elements and you cannot compute on them yourself. The only way \
to compute in G is to ask the challenger's oracle. Equal labels mean equal elements.

## Key generation
{keygen}

## Public values of the live instance
- N = {N}
{param_lines}- labels:
{label_lines}
Your goal is to find x (with h = g^x) and submit it.

## Oracle interface (HTTP/JSON at $ORACLE_URL = {url})
- `GET /instance`: the public values above, plus `budget` and `queries_used`.
- `POST /query` with `{{"ops": [op, ...]}}`, where each op is `["mul", a, b]` (a*b), \
`["inv", a]` (a^-1) or `["exp", a, k]` (a^k for any integer k, as an int or decimal string). \
`a` and `b` are labels, or `"$i"` for the i-th result of the same batch. Returns \
`{{"results": [labels...], "queries_used", "queries_remaining"}}`.
- `POST /submit` with `{{"x": "<decimal>"}}` returns `{{"correct": true|false, ...}}`.

**Cost model:** every op (mul, inv or exp) costs exactly one query, and so does every \
submission. Batching only saves round trips (up to 200000 ops per request). The live instance \
has a hard budget of **{budget} queries**, and a batch that would exceed it is rejected. The \
budget is shared by everything you do against the live oracle, including experiments.

`oracle_client.py` in your workspace wraps this API (`Oracle()` reads $ORACLE_URL). It also \
provides `MockOracle(N, x, budget=None, aux_powers=())`, a local oracle with the same \
interface and a secret you choose, which you can query for free when testing.

## Deliverables
1. Write `attack.py` in the workspace. `python attack.py` must connect to the oracle at \
$ORACLE_URL, read all parameters from `GET /instance` at runtime (never hard-code N, labels, \
x or other instance values), recover x within the budget, and submit it. After this session it \
will be run unchanged, in an empty directory containing only attack.py and oracle_client.py, against several **fresh \
instances** generated by the same key-generation procedure: new N, new labels and a new x, \
with parameters of the same kind and size and the same budget rule. It is scored on success \
and on the number of queries it uses.
2. Solve the live instance within its budget, for example by running your attack.py.

When both are done, call `finish` with a short explanation of your attack and its query cost.\
"""


def task_prompt(instance: dict, url: str) -> str:
    params = instance.get("params", {})
    param_lines = "".join(f"- {k} = {v}\n" for k, v in params.items())
    label_lines = "".join(f"  - {k} = {v}\n" for k, v in instance["labels"].items())
    return TASK_TEMPLATE.format(keygen=instance["keygen"], N=instance["N"], param_lines=param_lines,
                                label_lines=label_lines, url=url, budget=instance["budget"])
